### ISSUE TITLE
Error when started through Facebook Jest

### ISSUE THREAD

**Issue by thealjey** [medikoo/es6-symbol#9]
First of all, sorry if this isn't the right repo to post this issue into, but the error does occur in this module's **polyfill.js** file.
I'm trying to test [ESLint](https://www.npmjs.com/package/eslint) with [Jest](https://www.npmjs.com/package/jest-cli).
[ESLint](https://www.npmjs.com/package/eslint) uses [Escope](https://www.npmjs.com/package/escope), which in turn uses [es6-weak-map](https://www.npmjs.com/package/es6-weak-map), which in turn uses [es6-symbol](https://www.npmjs.com/package/es6-symbol).

Here's the trace:
```
TypeError: Property description must be an object: undefined

at defineProperty (native)
at eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es6-symbol/polyfill.js:18:3
at Symbol (eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es6-symbol/polyfill.js:36:19)
at eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es6-symbol/polyfill.js:49:21
at eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es6-symbol/index.js:3:59
at eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es6-iterator/index.js:9:16
at eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es6-iterator/array.js:6:22
at eslint/node_modules/escope/node_modules/es6-weak-map/node_modules/es6-iterator/get.js:4:22
at eslint/node_modules/escope/node_modules/es6-weak-map/polyfill.js:7:25
at eslint/node_modules/escope/node_modules/es6-weak-map/index.js:4:13
at eslint/node_modules/escope/lib/scope-manager.js:33:31
at eslint/node_modules/escope/lib/index.js:77:36
at eslint/lib/eslint.js:12:14
at eslint/lib/api.js:9:13
```

**Comment by medikoo** [comment]
@thealjey Assure that you use latest node.js (with corresponding npm) and latest eslint.
Also before installing them try to do 'npm cache clean' (npm had serious issues of installing incorrect packages versions if git versions were involved, and that will fix that.

If after above steps, you still have this issue, please prepare minimal test script that can reproduce it, on any machine.

I'm pretty sure it's some inconsitency in your setup, so pursuing above steps should fix it for you

**Comment by thealjey** [comment]
@medikoo 
thank you for responding so quickly!

I update everything on a daily basis:
1. NodeJS 0.12.5 (npm 2.11.3)
2. eslint 0.23.0 (es6-symbol 2.0.1)
3. jest-cli 0.4.13

Tried re-installing everything after `npm cache clean` as you suggested and the error still persists.

The minimal setup is:
```javascript
// package.json
{
  "scripts": {
    "test": "jest"
  },
  "devDependencies": {
    "eslint": "^0.23.0",
    "jest-cli": "^0.4.13"
  }
}

// index.js
require('eslint');

// __tests__/index-test.js
jest.dontMock('../index.js');
require('../index');
```

**Comment by medikoo** [comment]
@thealjey I've investigated it, and it's an issue of jest runner. It tries to mock all required dependencies,

when I logged what's a imported `d` or `d.gs` log gave me: `function (){return mockConstructor.apply(this,arguments);}`, and on `d.gs`, the proper function is not invoked, _undefined_ is returned, hence the error.

You should report that issue to jest project

**Comment by thealjey** [comment]
@medikoo 
I'll just turn automocking off, thank you very much for your help!
